### ISSUE TITLE
Feedback on 'The team behing the screen'

### ISSUE THREAD

**Issue by richierocks** [davidventuri/datacamp-blog-posts#1]
## Drop A/B testing

> The Content Quality team also designs and carries out A/B tests on content to test the effectiveness of improvements, then reports on their discoveries to develop best practices and inform future content development.

This is not yet true. (A/B testing feature not available.)

## Add something about analyzing data, responding to feedback

Suggested new first paragraph:

DataCamp prides itself on having the best quality data science curriculum around. The Content Quality team makes sure that statement stays true. A Content Quality Analyst's role is to work with our instructors to maintain and improve their content, based upon feedback from students and course performance data. They review text and code to ensure they are high quality, and write new automated tests in Python and R to provide personalized feedback for students.

## Richie's job title

> Content Quality Lead

Head of Content Quality, please.

## Include pictures of us?

Might make it more personal.

**Comment by davidventuri** [comment]
Thanks, @richierocks! I was going to do pictures but there would be a heck of a lot of pictures and the quality of pictures varied so I opted for LinkedIn profile links for aesthetic purposes. I hope to get a good picture of the content team in Dublin so we can include it at the end of the post. I'll let Marketing/Community have the final say on this in the meantime.

**Comment by davidventuri** [comment]
Fixed in https://github.com/davidventuri/datacamp-blog-posts/commit/609c3e7f826e064377b8881248c66f9bed8bbfcc and https://github.com/davidventuri/datacamp-blog-posts/commit/ed16c65ed2535ef15d565afdae8d19627be05f38
